export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USER_MODEL = 'USER_MODEL';
export const GAME_HISTORY_MODEL = 'GAME_HISTORY_MODEL';
export const TASK_MODEL = 'TASK_MODEL';
export const TASK_HISTORY_MODEL = 'TASK_HISTORY_MODEL';
export const REFERRAL_MODEL = 'REFERRAL_MODEL';
export const GAME_PROFILE_MODEL = 'GAME_PROFILE_MODEL';
export const TELEGRAM_USER_MODEL= 'TELEGRAM_USER_MODEL';